### ISSUE TITLE
NAs not allowed in subscripted assignments

### ISSUE THREAD

**Issue by lmorett** [neuropsychology/psycho.R#52]
I'm trying to compute d' and beta using the dprime function, and I receive the above error.  I'm trying to run the function on aggregated data that does not contain NAs (see below), so I'm not sure why I receive this error.  Do you have any suggestions as to why I'm receiving this error and of what I can do to ensure that the input is acceptable?

```
   Subject Hit FA Miss CR
1        1  18  7    0 11
2        2  18  2    0 16
3        4  18  2    0 16
4        5  16  0    2 18
5        6  14 14    4  4
6        7   7  0   11 18
7        8   8  7   10 11
8        9  11 10    7  8
9       13   8  6   10 12
10      14   4  1   14 17
11      15   0  1   18 17
12      16   2  2   16 16
13      17  10 11    8  7
14      18  16  0    2 18
15      19   7  6   11 12
16      20   3  2   15 16
17      21  18  1    0 17
18      22  18  1    0 17
19      23  15  6    3 12
20      24  17  7    1 11
21      25  18  0    0 18
22      26   2  2   16 16
23      27  10  1    8 17
24      28  16  3    2 15
25      29  15  0    3 18
26      31  17  0    1 18
27      32  10  9    8  9
28      33  18  2    0 16
29      36   3  6   15 12
30      37   8 11   10  7
31      38   1  2   17 16
32      39   5  0   13 18
33      40   0  0   18 18
34      41   5  8   13 10
35      42  15  2    3 16
36      43   1  0   17 18
37      44   1  0   17 18
38      45   4  4   14 14
39      46   7  7   11 11
40      47   8  7   10 11
```

**Comment by DominiqueMakowski** [comment]
@lmorett weird indeed, could you add some reproducible steps (with the code that generated the error), or attach a subset of data so I can check what's going on?

**Comment by lmorett** [comment]
@DominiqueMakowski sure, the data is attached.  (You'll need to open it in Excel and save as a .csv as GitHub won't allow me to upload the .csv version directly.)  The relevant R code is below:

[tone_differentiation_complete.xlsx](https://github.com/neuropsychology/psycho.R/files/2009629/tone_differentiation_complete.xlsx)

```
library(psycho)

## READ FILES
lexical_tone = read.csv('/Users/Laura12/Desktop/Grad_School/Lexical_tone/Data/tone_differentiation_complete.csv', header=TRUE)
(https://github.com/neuropsychology/psycho.R/files/2009619/tone_differentiation_complete.xlsx)

## COMPUTE SUM BY SUBJECT
lexical_tone_by_subject <- setNames(aggregate(list(lexical_tone$Hit, lexical_tone$FA, lexical_tone$Miss, lexical_tone$CR), list(lexical_tone$Subject), sum, na.rm=TRUE), c("Subject", "Hit", "FA", "Miss", "CR"))

##COMPUTE D-PRIME PER SUBJECT FOR NONLEXICAL AND LEXICAL TONE DISCRIMINATION
lexical_tone_by_subject_indices <- psycho::dprime(lexical_tone_by_subject$Hit, lexical_tone_by_subject$FA, lexical_tone_by_subject$Miss, lexical_tone_by_subject$CR)

```

**Comment by DominiqueMakowski** [comment]
@lmorett It was caused by a bug, I've updated the package, try reinstalling it (the github version) and then it should work:

```r
install.packages("devtools")
library("devtools")
install_github("neuropsychology/psycho.R")
library("psycho")
```

Let me know if it works!

**Comment by lmorett** [comment]
@DominiqueMakowski Thanks for looking into this--I reinstalled the package and it worked.

**Comment by mattdmoore** [comment]
Hiya, I've just had this exact same issue but reinstalling from github hasn't fixed it. 

The dprime function worked perfectly for two other subsets from the same data, but doesn't seem to like the last subset. I ran is.na() on the data and everything came back false, so I'm not sure what's going on.

Have you got any troubleshooting ideas? Cheers.

**Comment by DominiqueMakowski** [comment]
Dear @mattdmoore,

try `na.omit` instead of `is.na` :)

**Comment by AThompson2019** [comment]
Hello, I've just experienced the same issue. I've reinstalled the packages from GitHub. I also used na.omit but I'm still receiving the same error. This is the full error that I receive:

Error in a[fa_rate > hit_rate] <- b[fa_rate > hit_rate] : 
  NAs are not allowed in subscripted assignments

Do you have any ideas? 
Thanks for your help.

**Comment by DominiqueMakowski** [comment]
@AThompson2019 Could you provide a sample of the data so I can reproduce the error? Either attached here or via email (dom.makowski@gmail.com). Thanks!

**Comment by DominiqueMakowski** [comment]
@AThompson2019 allow me to answer here so it can be useful to others. The reason it shows this error is because, for several rows, you have 0 distractors (i.e., 0 correct rejections and 0 false alarms), which makes the computation of non-parametric indices (a' and b''d) impossible. Thus, the best way is to filter out these rows (where CR & FA == 0) before computing the indices. However, this could indicate that something isn't right from a methodological or preprocessing side. I hope it helps!

**Comment by BIOTRAC** [comment]
Hello together,
I encountered the same problem as described above. I followed the proposed procedures (i.e., updating the package direclty from the github repository, etc.) which seem not to resolve the error. Indeed, I could (at least partly) locate the problem:
**When the dprime function receives a matrix, or rather several vectors, as an input, like above, it does not calculate the indices for each row completely independently**. Below you can find an example where the input of 0 Hits, 0 Miss, 1 False Alarm (FA) and 0 Correct Rejections (CR) produces an error, but only if the dprime is applied on a matrix.
Thus assuming Hit, Miss, FA and CR can only take the value 0 and 1 I tried the funciton on each combination (those with 0 distractors were omitted). When Hit and Miss are both 0 dprime returns an error. However, when I pool those combinations separately with combinations that did not return an error into one matrix (see C1, C2, C3) the error disappears.

Therefore, if you still cannot resolve the problem one solution could be to locate the row that causes you the error by feeding only chunks of data into dprime and then calculate its indices separately.

`library("psycho")
A <- data.frame("Hit" = c(1,0,0), "Miss" = c(0,0,0), "FA" = c(1,1,1), "CR" = c(1,1,0))
# dprime parameters are fed with vectors or with their row elements individually 
All_rows <- dprime(n_hit = A$Hit, n_fa = A$FA, n_miss = A$Miss, n_cr = A$CR, adjusted = T); All_rows$dprime
First_two_rows <- dprime(n_hit = A$Hit[1:2], n_fa = A$FA[1:2], n_miss = A$Miss[1:2], n_cr = A$CR[1:2], adjusted = T); First_two_rows$dprime
First_row <- dprime(n_hit = A$Hit[1], n_fa = A$FA[1], n_miss = A$Miss[1], n_cr = A$CR[1], adjusted = T); First_row$dprime
Second_row <- dprime(n_hit = A$Hit[2], n_fa = A$FA[2], n_miss = A$Miss[2], n_cr = A$CR[2], adjusted = T); Second_row$dprime
Third_row <- dprime(n_hit = A$Hit[3], n_fa = A$FA[3], n_miss = A$Miss[3], n_cr = A$CR[3], adjusted = T); Third_row$dprime

#All combinations with 1 Hit (combinations with 0 distractors are omitted)
A <- data.frame("Hit" = c(1,1,1,1,1,1), "Miss" = c(1,1,1,0,0,0), "FA" = c(1,1,0,1,1,0), "CR" = c(1,0,1,1,0,1))
A_indices <- dprime(n_hit = A$Hit, n_fa = A$FA, n_miss = A$Miss, n_cr = A$CR, adjusted = T); A_indices$dprime

#Combinations with 0 Hit and 1 Miss
B <- data.frame("Hit" = c(0,0,0), "Miss" = c(1,1,1), "FA" = c(1,1,0), "CR" = c(1,0,1))
B_indices <- dprime(n_hit = B$Hit, n_fa = B$FA, n_miss = B$Miss, n_cr = B$CR, adjusted = T); B_indices$dprime

#Combinations with 0 Hit and 0 Miss --> produces an error
C <- data.frame("Hit" = c(0,0,0), "Miss" = c(0,0,0), "FA" = c(1,1,0), "CR" = c(1,0,1))
C_indices <- dprime(n_hit = C$Hit, n_fa = C$FA, n_miss = C$Miss, n_cr = C$CR, adjusted = T); C_indices$dprime

#Include each combination of C with valid values from A --> error disappeared
C1 <- data.frame("Hit" = c(1,1,0), "Miss" = c(1,1,0), "FA" = c(1,1,1), "CR" = c(1,1,1))
C1_indices <- dprime(n_hit = C1$Hit, n_fa = C1$FA, n_miss = C1$Miss, n_cr = C1$CR, adjusted = T); C1_indices$dprime
C2 <- data.frame("Hit" = c(1,1,0), "Miss" = c(1,1,0), "FA" = c(1,1,1), "CR" = c(1,1,0))
C2_indices <- dprime(n_hit = C2$Hit, n_fa = C2$FA, n_miss = C2$Miss, n_cr = C2$CR, adjusted = T); C2_indices$dprime
C3 <- data.frame("Hit" = c(1,1,0), "Miss" = c(1,1,0), "FA" = c(1,1,0), "CR" = c(1,1,1))
C3_indices <- dprime(n_hit = C3$Hit, n_fa = C3$FA, n_miss = C3$Miss, n_cr = C3$CR, adjusted = T); C3_indices$dprime

#Further combinations that produce an error
D <- data.frame("Hit" = c(1,1,0), "Miss" = c(1,1,0), "FA" = c(1,1,1), "CR" = c(1,0,1))
D_indices <- dprime(n_hit = D$Hit, n_fa = D$FA, n_miss = D$Miss, n_cr = D$CR, adjusted = T); D_indices$dprime

E <- data.frame("Hit" = c(1,0,0), "Miss" = c(0,0,0), "FA" = c(1,1,1), "CR" = c(1,1,0))
E_indices <- dprime(n_hit = E$Hit, n_fa = E$FA, n_miss = E$Miss, n_cr = E$CR, adjusted = T); E_indices$dprime`

**Comment by DominiqueMakowski** [comment]
Hi @BIOTRAC, thanks for the detailed report. Hopefully, it should be fixed (please check by updating the package from github). Let me know how it goes
